### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by kichappa** [hzhangxyz/keygen#1]
What is the hash value for 11.3? How do I obtain the hash values myself?

**Comment by hzhangxyz** [comment]
I don't know the hash for 11.3, try with hash for 11.2 first, maybe it is not changed.
If it does not work, you need to find it by yourself.
Just write a loop from 0000 to FFFF and call MathKernel to input key and password.

**Comment by kichappa** [comment]
I found out that hash doesn't actually matter.
